import { ClockService } from '@rs-tech-hub/nestjs-clock';
import { PrismaService, UserActivity, UserStatus } from '@rs-tech-hub/nestjs-prisma';
import { ServiceFacilitatorService } from '@rs-tech-hub/nestjs-service-operation';
import { UserCreateServiceInput } from './dto/service/input/user-create.service.input';
import { UserDeactivateActiveUserServiceInput } from './dto/service/input/user-deactivate-active-user.service.input';
import { UserDeactivatePendingUserServiceInput } from './dto/service/input/user-deactivate-pending-user.service.input';
import { UserGetAllServiceInput } from './dto/service/input/user-get-all.service.input';
import { UserLogActivityServiceInput } from './dto/service/input/user-log-activity.service.input';
import { UserUpdateAccountIdServiceInput } from './dto/service/input/user-update-accountId.service.input';
import { UserUpdateEmailServiceInput } from './dto/service/input/user-update-email.service.input';
import { UserUpdatePasswordServiceInput } from './dto/service/input/user-update-password.service.input';
import { UserUpdateRoleServiceInput } from './dto/service/input/user-update-role.service.input';
import { PaginatedUserServiceOutput } from './dto/service/output/paginated-user.service.output';
import { UserServiceOutput } from './dto/service/output/user.service.output';
import { UserActivityRepository } from './user-activity.repository';
import { UserRepository } from './user.repository';
export declare class UserService {
    protected readonly prisma: PrismaService;
    protected readonly userRepository: UserRepository;
    protected readonly userActivityRepository: UserActivityRepository;
    protected readonly clock: ClockService;
    protected readonly serviceFacilitator: ServiceFacilitatorService;
    private readonly logger;
    constructor(prisma: PrismaService, userRepository: UserRepository, userActivityRepository: UserActivityRepository, clock: ClockService, serviceFacilitator: ServiceFacilitatorService);
    private getOrThrow;
    private activate;
    private reactivate;
    private deactivate;
    private deactivateOnInactivity;
    private disable;
    private softDelete;
    private scheduleDeletion;
    private delete;
    logActivity(input: UserLogActivityServiceInput): Promise<UserActivity>;
    create(createUserInput: UserCreateServiceInput): Promise<UserServiceOutput>;
    activateById(id: string): Promise<UserServiceOutput>;
    reactivateById(id: string): Promise<UserServiceOutput>;
    updateEmail(updateUserEmailInput: UserUpdateEmailServiceInput): Promise<UserServiceOutput>;
    updatePassword(input: UserUpdatePasswordServiceInput): Promise<UserServiceOutput>;
    updateRole(input: UserUpdateRoleServiceInput): Promise<UserServiceOutput>;
    updateAccountId(input: UserUpdateAccountIdServiceInput): Promise<UserServiceOutput>;
    getById(id: string): Promise<UserServiceOutput>;
    getByEmail(email: string): Promise<UserServiceOutput>;
    getAll(input: UserGetAllServiceInput): Promise<PaginatedUserServiceOutput>;
    getAllByStatus(status: UserStatus): Promise<UserServiceOutput[]>;
    getAllByAccountId(accountId: string): Promise<UserServiceOutput[]>;
    emailExists(email: string): Promise<boolean>;
    getUsersCount(): Promise<number>;
    getActiveUsersCount(): Promise<number>;
    deactivateById(id: string): Promise<UserServiceOutput>;
    deactivatePendingUser(input: UserDeactivatePendingUserServiceInput): Promise<UserServiceOutput>;
    deactivateActiveUser(input: UserDeactivateActiveUserServiceInput): Promise<UserServiceOutput>;
    deactivateInactiveUsers(): Promise<UserServiceOutput[]>;
    disableById(id: string): Promise<UserServiceOutput>;
    disableDeactivatedUsers(gracePeriodInMonths: number): Promise<UserServiceOutput[]>;
    softDeleteById(id: string): Promise<UserServiceOutput>;
    scheduleForDeletionById(id: string): Promise<UserServiceOutput>;
    deleteById(id: string): Promise<UserServiceOutput>;
    softDeleteDisabledUsers(): Promise<UserServiceOutput[]>;
    scheduleSoftDeletedUsersForDeletion(gracePeriodInDays: number): Promise<UserServiceOutput[]>;
    deleteScheduledUsers(): Promise<UserServiceOutput[]>;
}
//# sourceMappingURL=user.service.d.ts.map