import { Prisma, PrismaService } from '@rs-tech-hub/nestjs-prisma';
import { ServiceFacilitatorService } from '@rs-tech-hub/nestjs-service-operation';
declare const UserRepositoryBase: new (prisma: PrismaService, serviceFacilitator: ServiceFacilitatorService) => {
    delegate: Prisma.UserDelegate<any, {}>;
    serviceFacilitator: ServiceFacilitatorService;
    prisma: PrismaService;
    getOperationName(operation: string): string;
    findWithSelect<T extends Record<string, true>>(where: unknown, select: T): Promise<{ [K in keyof T]: K extends "id" | "createdAt" | "Status" | "Role" | "email" | "issuerId" | "salt" | "hash" | "isVerified" | "activatedAt" | "deactivatedAt" | "disabledAt" | "softDeletedAt" | "isScheduledForDeletion" | "scheduledDeletionAt" | "accountId" | "updatedAt" ? {
        id: string;
        createdAt: Date;
        Status: import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role: import("@rs-tech-hub/nestjs-prisma").UserRole;
        email: string;
        issuerId: string | null;
        salt: string;
        hash: string;
        isVerified: boolean;
        activatedAt: Date | null;
        deactivatedAt: Date | null;
        disabledAt: Date | null;
        softDeletedAt: Date | null;
        isScheduledForDeletion: boolean;
        scheduledDeletionAt: Date | null;
        accountId: string;
        updatedAt: Date;
    }[K] : never; } | null>;
    findMany(where?: unknown, options?: {
        orderBy?: unknown;
        take?: number;
        skip?: number;
        select?: unknown;
        include?: unknown;
    } | undefined): Promise<any>;
    findManyWithSelect<T extends Record<string, true>>(where?: unknown, select?: T | undefined, options?: {
        orderBy?: unknown;
        take?: number;
        skip?: number;
    } | undefined): Promise<{ [K in keyof T]: K extends "id" | "createdAt" | "Status" | "Role" | "email" | "issuerId" | "salt" | "hash" | "isVerified" | "activatedAt" | "deactivatedAt" | "disabledAt" | "softDeletedAt" | "isScheduledForDeletion" | "scheduledDeletionAt" | "accountId" | "updatedAt" ? {
        id: string;
        createdAt: Date;
        Status: import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role: import("@rs-tech-hub/nestjs-prisma").UserRole;
        email: string;
        issuerId: string | null;
        salt: string;
        hash: string;
        isVerified: boolean;
        activatedAt: Date | null;
        deactivatedAt: Date | null;
        disabledAt: Date | null;
        softDeletedAt: Date | null;
        isScheduledForDeletion: boolean;
        scheduledDeletionAt: Date | null;
        accountId: string;
        updatedAt: Date;
    }[K] : never; }[]>;
    findOneWithSelect<T extends Record<string, true>>(where?: unknown, select?: T | undefined): Promise<{ [K in keyof T]: K extends "id" | "createdAt" | "Status" | "Role" | "email" | "issuerId" | "salt" | "hash" | "isVerified" | "activatedAt" | "deactivatedAt" | "disabledAt" | "softDeletedAt" | "isScheduledForDeletion" | "scheduledDeletionAt" | "accountId" | "updatedAt" ? {
        id: string;
        createdAt: Date;
        Status: import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role: import("@rs-tech-hub/nestjs-prisma").UserRole;
        email: string;
        issuerId: string | null;
        salt: string;
        hash: string;
        isVerified: boolean;
        activatedAt: Date | null;
        deactivatedAt: Date | null;
        disabledAt: Date | null;
        softDeletedAt: Date | null;
        isScheduledForDeletion: boolean;
        scheduledDeletionAt: Date | null;
        accountId: string;
        updatedAt: Date;
    }[K] : never; } | null>;
    findUnique(where: ({
        id: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        email: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        issuerId: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        accountId: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        id: string;
        email: string;
        issuerId: string;
        accountId: string;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }), options?: {
        select?: unknown;
        include?: unknown;
    } | undefined): Promise<any>;
    findUniqueWithSelect<T extends Record<string, true>>(where: ({
        id: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        email: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        issuerId: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        accountId: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        id: string;
        email: string;
        issuerId: string;
        accountId: string;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }), select: T): Promise<{ [K in keyof T]: K extends "id" | "createdAt" | "Status" | "Role" | "email" | "issuerId" | "salt" | "hash" | "isVerified" | "activatedAt" | "deactivatedAt" | "disabledAt" | "softDeletedAt" | "isScheduledForDeletion" | "scheduledDeletionAt" | "accountId" | "updatedAt" ? {
        id: string;
        createdAt: Date;
        Status: import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role: import("@rs-tech-hub/nestjs-prisma").UserRole;
        email: string;
        issuerId: string | null;
        salt: string;
        hash: string;
        isVerified: boolean;
        activatedAt: Date | null;
        deactivatedAt: Date | null;
        disabledAt: Date | null;
        softDeletedAt: Date | null;
        isScheduledForDeletion: boolean;
        scheduledDeletionAt: Date | null;
        accountId: string;
        updatedAt: Date;
    }[K] : never; } | null>;
    findWithInclude(where?: unknown, include?: unknown): Promise<any>;
    findManyWithInclude(where?: unknown, include?: unknown, options?: {
        orderBy?: unknown;
        take?: number;
        skip?: number;
    } | undefined): Promise<any>;
    findWithFields<K extends "id" | "createdAt" | "Status" | "Role" | "email" | "issuerId" | "salt" | "hash" | "isVerified" | "activatedAt" | "deactivatedAt" | "disabledAt" | "softDeletedAt" | "isScheduledForDeletion" | "scheduledDeletionAt" | "accountId" | "updatedAt">(where?: unknown, fields?: K[] | undefined): Promise<Pick<{
        id: string;
        createdAt: Date;
        Status: import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role: import("@rs-tech-hub/nestjs-prisma").UserRole;
        email: string;
        issuerId: string | null;
        salt: string;
        hash: string;
        isVerified: boolean;
        activatedAt: Date | null;
        deactivatedAt: Date | null;
        disabledAt: Date | null;
        softDeletedAt: Date | null;
        isScheduledForDeletion: boolean;
        scheduledDeletionAt: Date | null;
        accountId: string;
        updatedAt: Date;
    }, K> | null>;
    findManyWithFields<K extends "id" | "createdAt" | "Status" | "Role" | "email" | "issuerId" | "salt" | "hash" | "isVerified" | "activatedAt" | "deactivatedAt" | "disabledAt" | "softDeletedAt" | "isScheduledForDeletion" | "scheduledDeletionAt" | "accountId" | "updatedAt">(where?: unknown, fields?: K[] | undefined): Promise<Pick<{
        id: string;
        createdAt: Date;
        Status: import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role: import("@rs-tech-hub/nestjs-prisma").UserRole;
        email: string;
        issuerId: string | null;
        salt: string;
        hash: string;
        isVerified: boolean;
        activatedAt: Date | null;
        deactivatedAt: Date | null;
        disabledAt: Date | null;
        softDeletedAt: Date | null;
        isScheduledForDeletion: boolean;
        scheduledDeletionAt: Date | null;
        accountId: string;
        updatedAt: Date;
    }, K>[]>;
    create<T extends Record<string, boolean> | undefined = undefined>(data: ({
        Account?: undefined;
    } & Prisma.UserUncheckedCreateInput) | ({
        accountId?: undefined;
    } & Prisma.UserCreateInput), select?: T | undefined): Promise<any>;
    update<T extends Record<string, boolean> | undefined = undefined>(where: ({
        id: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        email: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        issuerId: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        accountId: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        id: string;
        email: string;
        issuerId: string;
        accountId: string;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }), data: ({
        Account?: undefined;
    } & Prisma.UserUncheckedUpdateInput) | ({
        accountId?: undefined;
    } & Prisma.UserUpdateInput), select?: T | undefined): Promise<any>;
    upsert<T extends Record<string, boolean> | undefined = undefined>(where: ({
        id: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        email: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        issuerId: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        accountId: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        id: string;
        email: string;
        issuerId: string;
        accountId: string;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }), create: ({
        Account?: undefined;
    } & Prisma.UserUncheckedCreateInput) | ({
        accountId?: undefined;
    } & Prisma.UserCreateInput), update: ({
        Account?: undefined;
    } & Prisma.UserUncheckedUpdateInput) | ({
        accountId?: undefined;
    } & Prisma.UserUpdateInput), select?: T | undefined): Promise<any>;
    delete(where: ({
        id: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        email: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        issuerId: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        accountId: string | undefined;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    }) | ({
        id: string;
        email: string;
        issuerId: string;
        accountId: string;
    } & {
        id?: string;
        email?: string;
        issuerId?: string;
        accountId?: string;
        AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        OR?: Prisma.UserWhereInput[];
        NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[];
        Status?: Prisma.EnumUserStatusFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserStatus;
        Role?: Prisma.EnumUserRoleFilter<"User"> | import("@rs-tech-hub/nestjs-prisma").UserRole;
        salt?: Prisma.StringFilter<"User"> | string;
        hash?: Prisma.StringFilter<"User"> | string;
        isVerified?: Prisma.BoolFilter<"User"> | boolean;
        activatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        deactivatedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        disabledAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        softDeletedAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        isScheduledForDeletion?: Prisma.BoolFilter<"User"> | boolean;
        scheduledDeletionAt?: Prisma.DateTimeNullableFilter<"User"> | Date | string | null;
        createdAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string;
        Account?: Prisma.XOR<Prisma.AccountScalarRelationFilter, Prisma.AccountWhereInput>;
        Activity?: Prisma.UserActivityListRelationFilter;
        Profile?: Prisma.XOR<Prisma.ProfileNullableScalarRelationFilter, Prisma.ProfileWhereInput> | null;
        RefreshTokens?: Prisma.RefreshTokenListRelationFilter;
        ActivationTokens?: Prisma.ActivationTokenListRelationFilter;
        passwordResetTokens?: Prisma.PasswordResetTokenListRelationFilter;
    })): Promise<any>;
    deleteMany(where?: unknown): Promise<any>;
    count(where?: unknown): Promise<number>;
    exists(where?: unknown): Promise<boolean>;
};
export declare class UserRepository extends UserRepositoryBase {
    constructor(prisma: PrismaService, serviceFacilitator: ServiceFacilitatorService);
}
export {};
//# sourceMappingURL=user.repository.d.ts.map