"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LICENSE_ERROR_HEARTBEAT_MAX_FAILED_ATTEMPTS = exports.LICENSE_ERROR_UNLICENSED_PRODUCTS_DETECTED = exports.LICENSE_ERROR_NO_PRODUCTS_REGISTERED = exports.LICENSE_ERROR_NO_PRODUCTS_LICENSED = exports.LICENSE_ERROR_LICENSE_NOT_VALID = exports.LICENSE_ERROR_MISSING_META_DATA = exports.LICENSE_ERROR_DETERMINING_LICENSE_TYPE = exports.LICENSE_ERROR_PRODUCT_NOT_LICENSED = exports.LICENSE_ERROR_DECREMENTING_USAGE_COUNT = exports.LICENSE_ERROR_USAGE_LIMIT_EXCEEDED = exports.LICENSE_ERROR_USAGE_LIMIT_REACHED = exports.LICENSE_ERROR_DEACTIVATING_KEY = exports.LICENSE_ERROR_ACTIVATING_KEY = exports.LICENSE_ERROR_DEACTIVATING_INSTANCE_FAILED = exports.LICENSE_ERROR_ACTIVATING_INSTANCE_FAILED = exports.LICENSE_ERROR_CHECKING_STATUS = exports.LICENSE_ERROR_PACKAGE_VALIDATION_FAILED = exports.LICENSE_ERROR_LICENSE_DEACTIVATION_FAILED = exports.LICENSE_ERROR_LICENSE_ACTIVATION_FAILED = exports.LICENSE_ERROR_LICENSE_VALIDATION_FAILED = exports.LICENSE_ERROR_LICENSE_KEY_VALIDATION_FAILED = exports.LICENSE_ERROR_LICENSE_NOT_ACTIVE = exports.LICENSE_ERROR_NO_LICENSE_PROVIDED = void 0;
exports.LICENSE_ERROR_NO_LICENSE_PROVIDED = 'license-error:no-license-provided';
exports.LICENSE_ERROR_LICENSE_NOT_ACTIVE = 'license-error:license-not-active';
exports.LICENSE_ERROR_LICENSE_KEY_VALIDATION_FAILED = 'license-error:failed-to-validate-license-key';
exports.LICENSE_ERROR_LICENSE_VALIDATION_FAILED = 'license-error:failed-to-validate-license';
exports.LICENSE_ERROR_LICENSE_ACTIVATION_FAILED = 'license-error:failed-to-activate-license';
exports.LICENSE_ERROR_LICENSE_DEACTIVATION_FAILED = 'license-error:failed-to-deactivate-license';
exports.LICENSE_ERROR_PACKAGE_VALIDATION_FAILED = 'license-error:failed-to-validate-registered-packages';
exports.LICENSE_ERROR_CHECKING_STATUS = 'license-error:failed-to-check-license-status';
exports.LICENSE_ERROR_ACTIVATING_INSTANCE_FAILED = 'license-error:failed-to-activate-license-instance';
exports.LICENSE_ERROR_DEACTIVATING_INSTANCE_FAILED = 'license-error:failed-to-deactivate-license-instance';
exports.LICENSE_ERROR_ACTIVATING_KEY = 'license-error:failed-to-activate-license-key';
exports.LICENSE_ERROR_DEACTIVATING_KEY = 'license-error:failed-to-deactivate-license-key';
exports.LICENSE_ERROR_USAGE_LIMIT_REACHED = 'license-error:usage-limit-reached';
exports.LICENSE_ERROR_USAGE_LIMIT_EXCEEDED = 'license-error:usage-limit-exceeded';
exports.LICENSE_ERROR_DECREMENTING_USAGE_COUNT = 'license-error:failed-to-decrement-usage-count';
exports.LICENSE_ERROR_PRODUCT_NOT_LICENSED = 'license-error:product-not-licensed';
exports.LICENSE_ERROR_DETERMINING_LICENSE_TYPE = 'license-error:failed-to-determine-license-type';
exports.LICENSE_ERROR_MISSING_META_DATA = 'license-error:missing-required-meta-data';
exports.LICENSE_ERROR_LICENSE_NOT_VALID = 'license-error:license-not-valid';
exports.LICENSE_ERROR_NO_PRODUCTS_LICENSED = 'license-error:no-products-licensed';
exports.LICENSE_ERROR_NO_PRODUCTS_REGISTERED = 'license-error:no-products-registered';
exports.LICENSE_ERROR_UNLICENSED_PRODUCTS_DETECTED = 'license-error:unlicensed-products-detected';
exports.LICENSE_ERROR_HEARTBEAT_MAX_FAILED_ATTEMPTS = 'license-error:heartbeat-max-failed-attempts-exceeded';
