import { JwtService } from '@nestjs/jwt';
import { AccountStarterRepository } from '@rs-tech-hub/nestjs-account-starter';
import { ClockService } from '@rs-tech-hub/nestjs-clock';
import { ProfileRepository } from '@rs-tech-hub/nestjs-profile';
import { RefreshTokenService } from '@rs-tech-hub/nestjs-refresh-token';
import { ServiceFacilitatorService, ServiceResult } from '@rs-tech-hub/nestjs-service-operation';
import { UserRepository, UserService, UserServiceOutput } from '@rs-tech-hub/nestjs-user';
import { VerifyEmailResolverOutput } from './dto/resolver/output/verifyEmail.resolver.output';
import { AuthConfirmSignupEmailInput } from './dto/service/input/auth-confirm-signup-email.service.input';
import { AuthLoginServiceInput } from './dto/service/input/auth-login.service.input';
import { AuthLogoutServiceInput } from './dto/service/input/auth-logout.service.input';
import { AuthRefreshTokenServiceInput } from './dto/service/input/auth-refresh-token.service.input';
import { AuthSignUpServiceInput } from './dto/service/input/auth-signup.service.input';
import { AuthValidateUserServiceInput } from './dto/service/input/auth-validate-user.service.input';
import { AuthUpdatePasswordServiceInput } from './dto/service/input/update-password.service.input';
import { AuthenticatedUserOutput } from './dto/service/output';
import { AuthCurrentUserServiceOutput } from './dto/service/output/auth-current-user.service.output.';
import { AuthLoginServiceOutput } from './dto/service/output/auth-login.service.output';
import { AuthLogoutServiceOutput } from './dto/service/output/auth-logout.service.output';
import { ActivationTokenService } from '@rs-tech-hub/nestjs-activation-token';
import { PasswordResetTokenService } from '@rs-tech-hub/nestjs-password-reset-token';
import { AuthActivateUserServiceInput } from './dto/service/input/auth-activate-user.service.input';
import { AuthRenewActivationTokenServiceInput } from './dto/service/input/auth-renew-activation-token.service.input';
import { AuthRequestPasswordResetServiceInput } from './dto/service/input/auth-request-password-reset.service.input';
import { AuthResetPasswordServiceInput } from './dto/service/input/auth-reset-password.service.input';
import { AuthRenewActivationTokenServiceOutput } from './dto/service/output/auth-renew-activation-token.service.output';
import { AuthRequestPasswordResetServiceOutput } from './dto/service/output/auth-request-password-reset.service.output';
import { AuthResponseOutput } from './dto/service/output/auth-response.service.output';
import { AuthSignupServiceOutput } from './dto/service/output/auth-signup.service.output';
import { UpdatePasswordServiceOutput } from './dto/service/output/update-password.service.output';
export declare class AuthStarterService {
    protected readonly accountRepository: AccountStarterRepository;
    protected readonly userService: UserService;
    protected readonly userRepository: UserRepository;
    protected readonly jwtService: JwtService;
    protected readonly refreshTokenService: RefreshTokenService;
    protected readonly passwordResetTokenService: PasswordResetTokenService;
    protected readonly serviceFacilitator: ServiceFacilitatorService;
    protected readonly profileRepository: ProfileRepository;
    protected readonly clock: ClockService;
    protected readonly activationTokenService: ActivationTokenService;
    private readonly logger;
    constructor(accountRepository: AccountStarterRepository, userService: UserService, userRepository: UserRepository, jwtService: JwtService, refreshTokenService: RefreshTokenService, passwordResetTokenService: PasswordResetTokenService, serviceFacilitator: ServiceFacilitatorService, profileRepository: ProfileRepository, clock: ClockService, activationTokenService: ActivationTokenService);
    verifyEmail(email: string): Promise<ServiceResult<string, VerifyEmailResolverOutput>>;
    private validateEmail;
    private checkPasswordSecurity;
    signUp(signUpInput: AuthSignUpServiceInput): Promise<ServiceResult<AuthSignUpServiceInput, AuthSignupServiceOutput>>;
    renewActivationToken(input: AuthRenewActivationTokenServiceInput): Promise<AuthRenewActivationTokenServiceOutput>;
    activateUser(input: AuthActivateUserServiceInput): Promise<boolean>;
    login(loginInput: AuthLoginServiceInput): Promise<ServiceResult<AuthLoginServiceInput, AuthLoginServiceOutput>>;
    refreshToken(refreshTokenInput: AuthRefreshTokenServiceInput): Promise<ServiceResult<AuthRefreshTokenServiceInput, AuthLoginServiceOutput>>;
    getCurrentUser(userId: string): Promise<ServiceResult<unknown, AuthCurrentUserServiceOutput>>;
    logout(logoutInput: AuthLogoutServiceInput): Promise<ServiceResult<AuthLogoutServiceInput, AuthLogoutServiceOutput>>;
    confirmSignupEmail(input: AuthConfirmSignupEmailInput): Promise<ServiceResult<AuthConfirmSignupEmailInput, AuthLoginServiceOutput>>;
    requestPasswordReset(input: AuthRequestPasswordResetServiceInput): Promise<AuthRequestPasswordResetServiceOutput>;
    resetPassword(input: AuthResetPasswordServiceInput): Promise<{
        success: boolean;
    }>;
    updatePassword(updatePasswordInput: AuthUpdatePasswordServiceInput): Promise<ServiceResult<AuthUpdatePasswordServiceInput, UpdatePasswordServiceOutput>>;
    protected validateUser(input: AuthValidateUserServiceInput): Promise<AuthenticatedUserOutput>;
    generateAuthResponse(user: UserServiceOutput): Promise<AuthResponseOutput>;
    generateSalt(): Promise<string>;
    generateHash(password: string, salt: string): Promise<string>;
    validatePassword(password: string, hash: string): Promise<boolean>;
}
//# sourceMappingURL=auth-starter.service.d.ts.map