"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REFRESH_TOKEN_REVOKED = exports.REFRESH_TOKEN_INVALID = exports.REFRESH_TOKEN_EXPIRED = exports.USER_NOT_ACTIVATED = exports.USER_NO_PASSWORD_FOUND = exports.USER_IS_CURRENT_EMAIL = exports.USER_DOES_NOT_EXISTS = exports.USER_ALREADY_EXISTS = exports.USER_ALREADY_ACTIVATED = exports.USER_ACTIVATION_KEY_INVALID = exports.UNAUTHORIZED = exports.STRIPE_NO_ACTIVE_SUBSCRIPTION = exports.STRIPE_CUSTOMER_NOT_FOUND = exports.DEMO_ACCOUNT_CREATION_LIMIT_REACHED = exports.CREDITS_LIMIT_REACHED_CHECK_LIMIT = exports.CREDITS_LIMIT_REACHED = exports.CREDITS_DAILY_LIMIT_REACHED = exports.AUTH_ERROR_INVALID_CREDENTIALS = exports.ACCOUNTSUBSCRIPTION_DOES_NOT_EXISTS = void 0;
exports.ACCOUNTSUBSCRIPTION_DOES_NOT_EXISTS = 'subscription-error:account-subscription-does-not-exist';
exports.AUTH_ERROR_INVALID_CREDENTIALS = 'user-error:auth-invalid-credentials';
exports.CREDITS_DAILY_LIMIT_REACHED = 'user-error:credits-daily-limit-reached';
exports.CREDITS_LIMIT_REACHED = 'user-error:credits-limit-reached';
exports.CREDITS_LIMIT_REACHED_CHECK_LIMIT = 'user-error:credits-limit-reached-check-limit';
exports.DEMO_ACCOUNT_CREATION_LIMIT_REACHED = 'user-error:max-daily-demo-accounts-created-reached';
exports.STRIPE_CUSTOMER_NOT_FOUND = 'user-error:stripe-customer-not-found';
exports.STRIPE_NO_ACTIVE_SUBSCRIPTION = 'user-error:strip-no-active-subscription';
exports.UNAUTHORIZED = 'user-error:unauthorized';
exports.USER_ACTIVATION_KEY_INVALID = 'user-error:activation-key-invalid';
exports.USER_ALREADY_ACTIVATED = 'user-error:user-already-activated';
exports.USER_ALREADY_EXISTS = 'user-error:user-already-exists';
exports.USER_DOES_NOT_EXISTS = 'user-error:user-does-not-exist';
exports.USER_IS_CURRENT_EMAIL = 'user-error:is-current-email';
exports.USER_NO_PASSWORD_FOUND = 'user-error:no-password-found';
exports.USER_NOT_ACTIVATED = 'user-error:user-not-activated';
exports.REFRESH_TOKEN_EXPIRED = 'user-error:refresh-token-expired';
exports.REFRESH_TOKEN_INVALID = 'user-error:refresh-token-invalid';
exports.REFRESH_TOKEN_REVOKED = 'user-error:refresh-token-revoked';
