export type { AuthenticatedUser } from './lib/interfaces/authenticated-user.interface';
export type { JwtPayload } from './lib/interfaces/jwt-payload.interface';
export type { AuthConfig } from './lib/config/auth.config.interface';
export type { BasicAuthConfig, JwtConfig, ServiceAuthConfig, } from './lib/config/jwt.config.interface';
export { CurrentUserId } from './lib/decorators/current-user-id.decorator';
export { CurrentUser } from './lib/decorators/current-user.decorator';
export { RefreshToken } from './lib/decorators/refresh-token.decorator';
export { AuthGuard } from './lib/guards/auth.guard';
export { BasicAuthGuard } from './lib/guards/basic-auth.guard';
export { GqlAuthGuard } from './lib/guards/gql-auth.guard';
export { JwtRefreshGuard } from './lib/guards/jwt-refresh.guard';
export { ServiceAuthGuard } from './lib/guards/service-auth.guard';
export { JwtRefreshStrategy } from './lib/strategies/jwt-refresh.strategy';
export { JwtStrategy } from './lib/strategies/jwt.strategy';
export { JwtGlobalModule } from './lib/global/jwt-global.module';
export { PassportGlobalModule } from './lib/global/passport-global.module';
export { IS_PUBLIC_KEY, Public } from './lib/reflectors/isPublic.reflector';
export { extractRefreshToken, extractTokenFromHeader, getRequestFromContext, } from './lib/utils/context.utils';
export * from './lib/errors';
//# sourceMappingURL=index.d.ts.map